import {SlideAxleNoRestrictionMaxLength,SlideAxleRestriction,State} from "./types.ts";

export enum SlideAxleRestrictionsDivider {str = "-------------------------------------"}

export const slideAxleRestrictedStates:Array<SlideAxleRestriction|SlideAxleRestrictionsDivider> = [
   SlideAxleRestrictionsDivider.str,
   {state: State.CA, kingpinToTandemMaxLength: 40, measurementReference: "to rear axle"},
   SlideAxleRestrictionsDivider.str,
   {state: State.RI, kingpinToTandemMaxLength: 41, measurementReference: "to rear axle"},
   SlideAxleRestrictionsDivider.str,
   {state: State.AL, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.AK, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.FL, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.MD, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.NH, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.NJ, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.NC, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.PA, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.SC, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.TN, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.VT, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.VA, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   {state: State.WV, kingpinToTandemMaxLength: 41, measurementReference: "to tandem center"},
   SlideAxleRestrictionsDivider.str,
   {state: State.CT, kingpinToTandemMaxLength: 43, measurementReference: "to rear axle"},
   {state: State.IN, kingpinToTandemMaxLength: 43, measurementReference: "to rear axle"},
   {state: State.NY, kingpinToTandemMaxLength: 43, measurementReference: "to rear axle"},
   SlideAxleRestrictionsDivider.str,
   {state: State.MN, kingpinToTandemMaxLength: 43, measurementReference: "to tandem center"},
   {state: State.WI, kingpinToTandemMaxLength: 43, measurementReference: "to tandem center"},
   SlideAxleRestrictionsDivider.str,
   {state: State.IL, kingpinToTandemMaxLength: 45.5, measurementReference: "to rear axle"},
   {state: State.ME, kingpinToTandemMaxLength: 45.5, measurementReference: "to rear axle"},
];

export const unrestrictedLength:SlideAxleNoRestrictionMaxLength = 48
export const unrestrictedReference = "to tandem center"

export const slideAxleUnrestrictedStates:Array<SlideAxleRestriction> = [
   {state: State.AZ, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.AR, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.CO, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.DE, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.GA, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.HI, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.ID, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.IA, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.KS, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.KY, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.LA, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.MA, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.MI, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.MS, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.MO, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.MT, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.NE, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.NV, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.NM, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.ND, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.OH, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.OK, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.OR, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.SD, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.TX, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.UT, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.WA, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
   {state: State.WY, kingpinToTandemMaxLength: unrestrictedLength, measurementReference: unrestrictedReference},
];